version: '3.0'
services:
  backend:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      POSTGRES_DB: go_app
      POSTGRES_HOST: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432

  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=go_app
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
