version: '3.0'
services:
  go-api:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      POSTGRES_DB: go_app
      POSTGRES_HOST: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432

  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=go_app
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password

  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on: 
      - go-api