- name: Configure
  hosts: all
  remote_user: root
  handlers:
    - name: restart ufw
      service: name=ufw state=restarted

  tasks: 
    - name: Install ufw
      apt: package=ufw state=present

    - name: Enable ufw logging
      ufw: logging=on

    - name: Configure ufw defaults
      ufw: direction={{ item.direction }} policy={{ item.policy }}
      with_items:
        - { direction: 'incoming', policy: 'deny' }
        - { direction: 'outgoing', policy: 'allow' }
      notify:
        - restart ufw

    - name: Configure ufw rules
      ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
      with_items:
        - { rule: 'allow', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
        - { rule: 'allow', port: '80', proto: 'tcp' }
        - { rule: 'allow', port: '443', proto: 'tcp' }

      notify:
        - restart ufw

    - name: Update Repos
      shell: apt update