---
- name: docker-compose
  hosts: all
  remote_user: root
  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/Akashi23/go-webservice-test.git
        dest: /go-webservice-test
        clone: yes
        update: yes
    
    - name: Docker compose
      shell: docker-compose build && docker-compose up -d